cas:
  # Required properties
  server-url-prefix: https://cas.localhost/
  server-login-url: https://cas.localhost/login
  client-host-url: https://bootiful.localhost

  # Optional properties
  authentication-url-patterns: [/protected, /protected2]
  validation-url-patterns: [/protected, /protected2]
  # request-wrapper-url-patterns: [/protected, /protected2]
  # assertion-thread-local-url-patterns: [/*]

  # One of CAS3, CAS, or SAML. The default is CAS3 if not explicitly specified
  validation-type: CAS3

  # gateway: true
  use-session: false
  # redirect-after-validation: false
  # allowed-proxy-chains: ['https://bootiful.localhost/proxy1', 'https://bootiful.localhost/proxy2']
  # proxy-callback-url: https://bootiful.localhost/proxy-callback
  # proxy-receptor-url: /proxy-callback
  # accept-any-proxy: true

# This variable is used in the code, see ${casLogoutUrl} in MainController.groovy
casLogoutUrl: https://cas.localhost/logout?service=https://bootiful.localhost/

spring:
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false
  groovy:
    template:
      cache: false

# Sample embedded servlet container SSL config and session tracking mode. Change as appropriate for your local deployment environment
server:
  port: 8000
  session:
    cookie:
      http-only: true
    tracking-modes: COOKIE
  ssl:
    enabled: false
    key-store: /etc/cas/thekeystore
    key-store-password: changeit
  # For 'renew' param, latest Java CAS client requires that it is set as the Servlet 'context-param'. This is how to easily set it in Spring Boot
  # context-parameters.renew: true


logging.level:
  org.jasig.cas: DEBUG
