version: '3.7'

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      default:
        aliases:
          # This allows the other containers to also reach the services through
          #   this public address (as opposed to using hostnames)
          - keycloak.localhost
          - httpbin.localhost
          - httpbin-two.localhost
          - ace.localhost

  postgres:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    container_name: keycloak-postgres

  keycloak:
    image: jboss/keycloak:9.0.2
    volumes:
      - ./compose/keycloak/https/:/etc/x509/https
      - ./compose/keycloak/setup.sh/:/setup.sh
      - ./compose/keycloak/start.sh/:/start.sh
    entrypoint: /start.sh
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      # KEYCLOAK_LOGLEVEL: DEBUG
    depends_on:
      - postgres
    container_name: keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.keycloak.rule=Host(`keycloak.localhost`) || HostSNI(`keycloak.localhost`)"
      - "traefik.tcp.routers.keycloak.tls.passthrough=true"
      - "traefik.tcp.routers.keycloak.entrypoints=websecure"
      - "traefik.tcp.services.keycloak.loadbalancer.server.port=8443"

  gatekeeper:
    image: alpine:3.8
    volumes:
      - ./compose/gatekeeper/config.yml:/gatekeeper/config.yml:ro
      - ./compose/setup.sh:/gatekeeper/setup.sh:ro
      - ./compose/start.sh:/gatekeeper/start.sh:ro
      - ./compose/keycloak/https/tls.crt/:/usr/local/share/ca-certificates/tls.crt:ro
    entrypoint: /gatekeeper/start.sh
    depends_on:
      - keycloak
    container_name: httpbin-gatekeeper
    environment:
      GATEKEEPER_CLIENT_ID: httpbin
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.httpbin.rule=Host(`httpbin.localhost`) || HostSNI(`httpbin.localhost`)"
      - "traefik.tcp.routers.httpbin.tls.passthrough=true"
      - "traefik.tcp.routers.httpbin.entrypoints=websecure"
      - "traefik.tcp.services.httpbin.loadbalancer.server.port=443"

  httpbin:
    image: kennethreitz/httpbin
    depends_on:
      - gatekeeper
    container_name: httpbin-protected-app

  gatekeeper-two:
    image: alpine:3.8
    volumes:
      - ./compose/gatekeeper-two/config.yml:/gatekeeper/config.yml:ro
      - ./compose/setup.sh:/gatekeeper/setup.sh:ro
      - ./compose/start.sh:/gatekeeper/start.sh:ro
      - ./compose/keycloak/https/tls.crt/:/usr/local/share/ca-certificates/tls.crt:ro
    entrypoint: /gatekeeper/start.sh
    depends_on:
      - keycloak
    container_name: httpbin-two-gatekeeper
    environment:
      GATEKEEPER_CLIENT_ID: httpbin-two
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.httpbin-two.rule=Host(`httpbin-two.localhost`) || HostSNI(`httpbin-two.localhost`)"
      - "traefik.tcp.routers.httpbin-two.tls.passthrough=true"
      - "traefik.tcp.routers.httpbin-two.entrypoints=websecure"
      - "traefik.tcp.services.httpbin-two.loadbalancer.server.port=443"

  httpbin-two:
    image: kennethreitz/httpbin
    depends_on:
      - gatekeeper-two
    container_name: httpbin-two-protected-app

  gatekeeper-ace:
    image: alpine:3.8
    volumes:
      - ./compose/gatekeeper-ace/config.yml:/gatekeeper/config.yml:ro
      - ./compose/setup.sh:/gatekeeper/setup.sh:ro
      - ./compose/start.sh:/gatekeeper/start.sh:ro
      - ./compose/keycloak/https/tls.crt/:/usr/local/share/ca-certificates/tls.crt:ro
    entrypoint: /gatekeeper/start.sh
    depends_on:
      - keycloak
    container_name: ace-gatekeeper
    environment:
      GATEKEEPER_CLIENT_ID: ace
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.ace.rule=Host(`ace.localhost`) || HostSNI(`ace.localhost`)"
      - "traefik.tcp.routers.ace.tls.passthrough=true"
      - "traefik.tcp.routers.ace.entrypoints=websecure"
      - "traefik.tcp.services.ace.loadbalancer.server.port=443"

  ace:
    image: openjdk:8-alpine
    container_name: ace
    volumes:
      - ./ace:/ace
      - ./compose/ace/start.sh:/start.sh:ro
      - ./compose/keycloak/https/tls.crt/:/tmp/tls.crt:ro
    working_dir: /ace
    entrypoint: /start.sh

volumes:
  postgres-data:
