version: '3'

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak:9.0.2
    volumes:
      - ./compose/keycloak/https/:/etc/x509/https
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres

  gatekeeper:
    image: alpine:3.8
    volumes:
      - ./compose/gatekeeper/:/gatekeeper
      - ./compose/keycloak/https/tls.crt/:/usr/local/share/ca-certificates/tls.crt:ro
    entrypoint: /gatekeeper/start.sh
    ports:
      - 7443:443
    depends_on:
      - keycloak

  httpbin:
    image: kennethreitz/httpbin
    depends_on:
      - gatekeeper

  gatekeeper-two:
    image: alpine:3.8
    volumes:
      - ./compose/gatekeeper-two/:/gatekeeper
      - ./compose/keycloak/https/tls.crt/:/usr/local/share/ca-certificates/tls.crt:ro
    entrypoint: /gatekeeper/start.sh
    ports:
      - 6443:443
    depends_on:
      - keycloak

  httpbin-two:
    image: kennethreitz/httpbin
    depends_on:
      - gatekeeper-two

volumes:
  postgres-data:
