version: '3.7'

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      default:
        aliases:
          # This allows the other containers to also reach the services through
          #   this public address (as opposed to using hostnames)
          - cas.localhost
          - bootiful.localhost

  cas:
    image: apereo/cas:v6.1.3
    container_name: cas
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.cas.rule=HostSNI(`cas.localhost`)"
      - "traefik.tcp.routers.cas.entrypoints=websecure"
      - "traefik.tcp.routers.cas.tls.passthrough=true"
      - "traefik.tcp.services.cas.loadbalancer.server.port=8443"
    volumes:
      - ./compose/cas/services:/services:ro
      - ./compose/cas/start.sh:/start.sh:ro
      - ./compose/cas/certs/cas.p12:/tmp/cas.p12:ro
    entrypoint: /start.sh

  bootiful:
    image: openjdk:8-alpine
    container_name: bootiful
    volumes:
      - ./compose/bootiful/start.sh:/start.sh:ro
      - ./compose/bootiful/application.yml:/tmp/application.yml:ro
      - ./compose/cas/certs/tls.crt:/tmp/tls.crt:ro
    entrypoint: /start.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bootiful.rule=Host(`bootiful.localhost`)"
      - "traefik.http.routers.bootiful.entrypoints=websecure"
      - "traefik.http.routers.bootiful.tls=true"
      - "traefik.http.routers.bootiful.tls.domains[0].main=bootiful.localhost"
      - "traefik.http.services.bootiful.loadbalancer.server.port=80"
