client-id: httpbin-two
discovery-url: https://keycloak.test:8443/auth/realms/applications
encryption-key: sKBQzdR45IyzbfuYhSXnHR3rRXfW5wGg

# Turn on debug
verbose: true

enable-refresh-tokens: true

enable-self-signed-tls: true
listen: :443
redirection-url: https://httpbin-two.test:6443
upstream-url: http://httpbin-two

enable-default-deny: true
resources:
# Whitelist everything needed to show API landing page
- uri: /
  methods:
  - GET
  white-listed: true
- uri: /spec.json
  methods:
  - GET
  white-listed: true
- uri: /flasgger_static/*
  methods:
  - GET
  white-listed: true
